CREATE TABLE workspaces (
    workid SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
	description VARCHAR(50),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ownerid INT,
    FOREIGN KEY (ownerid) REFERENCES users(id) ON DELETE CASCADE
);